-- ==============================================================================
-- 2024-2025 봉사연도 구글시트 실제 데이터 마이그레이션 SQL
-- 충돌 방지 및 안전한 외래키(UUID) 연동 스크립트
-- ==============================================================================

-- 0. 제약조건 안전 완화 (기존 테이블 호환)
ALTER TABLE public.publishers DROP CONSTRAINT IF EXISTS publishers_position_check;
ALTER TABLE public.publishers ADD CONSTRAINT publishers_position_check CHECK (position IN ('장로', '봉사의 종', '봉종', '일반', ''));

-- 1. 2024-2025 봉사연도 등록 (year_name = '2025')
INSERT INTO public.service_years (year_name, is_current, start_date, end_date)
VALUES ('2025', false, '2024-09-01', '2025-08-31')
ON CONFLICT (year_name) DO UPDATE SET start_date = EXCLUDED.start_date, end_date = EXCLUDED.end_date;

-- 2. 집단 등록 (효자, 수어, 석사, 현대, 운교, 퇴계 등)
-- id를 하드코딩하지 않아 기존 그룹과 충돌 없이 안전하게 매핑됩니다.
INSERT INTO public.groups (name, overseer_name, display_order)
VALUES 
  ('효자', '효자 감독자', 1),
  ('수어', '수어 감독자', 2),
  ('석사', '석사 감독자', 3),
  ('현대', '현대 감독자', 4),
  ('운교', '운교 감독자', 5),
  ('퇴계', '퇴계 감독자', 6)
ON CONFLICT (name) DO NOTHING;

-- 3. 2024-2025 전도인 명단 등록
-- 기존 전도인은 그룹/정보를 유지하고, 전출자/신규자만 안전하게 추가됩니다.
INSERT INTO public.publishers (name, group_id, gender, hope, position, pioneer_status, is_active)
SELECT 
  v.name,
  g.id,
  '남',
  '다른 양',
  v.position,
  v.pioneer_status,
  v.is_active
FROM (VALUES
  ('강미숙', '효자', '일반', '일반', true),
  ('강석찬', '효자', '장로', 'RP', true),
  ('강선아', '수어', '일반', 'RP', true),
  ('강영아', '효자', '일반', '일반', true),
  ('강정구', '석사', '일반', 'RP', true),
  ('권선', '석사', '일반', 'RP', true),
  ('권윤', '현대', '일반', 'RP', true),
  ('김기림', '수어', '일반', 'RP', true),
  ('김랑임', '운교', '일반', 'RP', true),
  ('김명희', '석사', '일반', 'RP', true),
  ('김미옥', '석사', '일반', '일반', true),
  ('김상만', '운교', '장로', '일반', true),
  ('김승연', '운교', '장로', 'RP', true),
  ('김승일', '수어', '장로', 'RP', true),
  ('김인자', '수어', '일반', 'RP', true),
  ('김정남', '현대', '일반', 'RP', true),
  ('김정민', '효자', '장로', 'RP', true),
  ('김정숙', '현대', '일반', 'RP', true),
  ('김주연', '운교', '일반', 'RP', true),
  ('김준', '현대', '장로', 'RP', true),
  ('김지애', '효자', '일반', 'AP', true),
  ('김태민', '운교', '봉사의 종', 'RP', true),
  ('김태호', '운교', '장로', 'AP', true),
  ('김하나', '효자', '일반', 'AP', true),
  ('김하연', '운교', '일반', 'RP', true),
  ('김홍철', '현대', '일반', '일반', true),
  ('김희웅', '현대', '장로', 'RP', true),
  ('김희정', '석사', '일반', 'RP', true),
  ('문경주', '수어', '장로', 'RP', true),
  ('문광호', '운교', '장로', 'RP', true),
  ('문정은', '운교', '일반', 'RP', true),
  ('박근미', '현대', '일반', '일반', true),
  ('박미희', '현대', '일반', 'RP', true),
  ('박해숙', '운교', '일반', 'RP', true),
  ('박형빈', '석사', '일반', 'RP', true),
  ('손지영', '수어', '일반', 'RP', true),
  ('신경희', '효자', '일반', '일반', true),
  ('신미연', '효자', '일반', '일반', true),
  ('신범선', '석사', '장로', 'RP', true),
  ('심인숙', '석사', '일반', 'RP', true),
  ('오경숙', '석사', '일반', '일반', true),
  ('우성제', '석사', '봉사의 종', 'AP', true),
  ('위영희', '운교', '일반', 'RP', true),
  ('이경진', '수어', '장로', 'RP', true),
  ('이경훈', '효자', '봉사의 종', 'AP', true),
  ('이기운', '운교', '봉사의 종', 'AP', true),
  ('이순금', '효자', '일반', '일반', true),
  ('이순주', '수어', '일반', 'RP', true),
  ('이슬아', '수어', '일반', 'RP', true),
  ('이용규', '석사', '봉사의 종', 'AP', true),
  ('이은옥', '석사', '일반', '일반', true),
  ('이은우', '수어', '봉사의 종', 'AP', true),
  ('이재춘', '현대', '일반', 'AP', true),
  ('이정구', '석사', '일반', 'AP', true),
  ('이정인', '수어', '장로', 'RP', true),
  ('이채민', '현대', '일반', '일반', true),
  ('이춘자', '효자', '일반', '일반', true),
  ('이혜미', '현대', '일반', 'RP', true),
  ('이혜숙', '수어', '일반', 'RP', true),
  ('인혜진', '운교', '일반', 'RP', true),
  ('임연순', '운교', '일반', 'RP', true),
  ('장지은', '수어', '일반', 'RP', true),
  ('전은아', '수어', '일반', 'RP', true),
  ('전인숙', '수어', '일반', 'RP', true),
  ('전재관', '현대', '장로', 'RP', true),
  ('전지훈', '효자', '봉사의 종', 'RP', true),
  ('전진혁', '석사', '장로', 'AP', true),
  ('전채균', '운교', '일반', 'AP', true),
  ('전혜인', '수어', '일반', 'RP', true),
  ('전호진', '수어', '봉사의 종', 'RP', true),
  ('정금석', '현대', '일반', '일반', true),
  ('정명희', '운교', '일반', '일반', true),
  ('정복희', '효자', '일반', 'RP', true),
  ('정승헌', '현대', '봉사의 종', 'RP', true),
  ('정태희', '수어', '일반', 'AP', true),
  ('정향순', '석사', '일반', '일반', true),
  ('조월동', '수어', '일반', 'AP', true),
  ('조인형', '수어', '일반', 'RP', true),
  ('조행진', '효자', '일반', 'RP', true),
  ('주우규', '수어', '일반', 'RP', true),
  ('진선미', '효자', '일반', '일반', true),
  ('채영진', '현대', '장로', 'RP', true),
  ('최선율', '수어', '일반', 'AP', true),
  ('최수정', '석사', '일반', '일반', true),
  ('최승준', '수어', '봉사의 종', 'RP', true),
  ('최현수', '수어', '봉사의 종', 'AP', true),
  ('한명숙', '효자', '일반', 'RP', true),
  ('허율', '석사', '일반', '일반', true),
  ('황선영', '운교', '일반', '일반', true),
  ('황은영', '운교', '일반', '일반', true),
  ('김명철', '석사', '장로', 'AP', false),
  ('김선혁', '퇴계', '봉사의 종', 'AP', false),
  ('김세나', '퇴계', '일반', 'RP', false),
  ('김수빈', '퇴계', '일반', 'RP', false),
  ('김영일', '효자', '장로', 'RP', false),
  ('김지영', '퇴계', '일반', 'RP', false),
  ('김하영', '퇴계', '일반', 'RP', false),
  ('손인환', '수어', '봉사의 종', 'RP', false),
  ('신경옥', '효자', '일반', 'AP', false),
  ('안명길', '현대', '봉사의 종', 'RP', false),
  ('오규원', '수어', '봉사의 종', 'RP', false),
  ('이창희', '현대', '일반', 'RP', false),
  ('임예린', '퇴계', '일반', '일반', false),
  ('임윤섭', '퇴계', '장로', 'RP', false),
  ('장은주', '퇴계', '일반', 'RP', false),
  ('전종성', '운교', '장로', 'RP', false),
  ('조규설', '현대', '일반', '일반', false),
  ('황민숙', '운교', '일반', 'RP', false),
  ('장정자', '현대', '일반', '일반', false)
) AS v(name, group_name, position, pioneer_status, is_active)
LEFT JOIN public.groups g ON g.name = v.group_name
ON CONFLICT (name) DO UPDATE SET
  group_id = COALESCE(public.publishers.group_id, EXCLUDED.group_id);

-- 4. 2024-2025 12개월 마감 상태 삽입
INSERT INTO public.monthly_statuses (service_year_id, month, is_closed)
SELECT 
  sy.id,
  m.month,
  true
FROM public.service_years sy
CROSS JOIN (VALUES
  ('9월'), ('10월'), ('11월'), ('12월'),
  ('1월'), ('2월'), ('3월'), ('4월'),
  ('5월'), ('6월'), ('7월'), ('8월')
) AS m(month)
WHERE sy.year_name = '2025'
ON CONFLICT (service_year_id, month) DO UPDATE SET is_closed = EXCLUDED.is_closed;

-- 5. 2024-2025 월별 봉사 보고서 삽입 (총 1,105건)

INSERT INTO public.monthly_reports (service_year_id, publisher_id, month, participated, hours, bible_studies, remarks, submitted_at)
SELECT 
  sy.id,
  p.id,
  v.month,
  v.participated,
  v.hours,
  v.bible_studies,
  v.remarks::JSONB,
  '2024-09-01 00:00:00+00'::TIMESTAMPTZ
FROM (VALUES
  ('강미숙', '9월', true, 0, 0, '[]'::text),
  ('강석찬', '9월', true, 52, 0, '[]'::text),
  ('강선아', '9월', true, 51, 0, '[]'::text),
  ('강영아', '9월', true, 0, 0, '[]'::text),
  ('강정구', '9월', true, 60, 0, '[]'::text),
  ('권선', '9월', true, 51, 0, '[]'::text),
  ('김랑임', '9월', true, 53, 0, '[]'::text),
  ('김명철', '9월', true, 0, 0, '[]'::text),
  ('김미옥', '9월', true, 0, 0, '[]'::text),
  ('김상만', '9월', true, 0, 0, '[]'::text),
  ('김선혁', '9월', true, 42, 0, '[]'::text),
  ('김세나', '9월', true, 63, 1, '[]'::text),
  ('김수빈', '9월', true, 60, 0, '[]'::text),
  ('김승연', '9월', true, 42, 0, '[]'::text),
  ('김승일', '9월', true, 42, 0, '[]'::text),
  ('김영일', '9월', true, 52, 0, '[]'::text),
  ('김인자', '9월', true, 62, 2, '[]'::text),
  ('김정남', '9월', true, 55, 0, '[]'::text),
  ('김정민', '9월', true, 47, 0, '[]'::text),
  ('김정숙', '9월', true, 62, 0, '[]'::text),
  ('김주연', '9월', true, 84, 0, '[]'::text),
  ('김준', '9월', true, 55, 0, '[]'::text),
  ('김지애', '9월', true, 13, 0, '[]'::text),
  ('김지영', '9월', true, 7, 0, '[{"type":"비고","hours":"0","etc":"LDC: 48시간"}]'::text),
  ('김태민', '9월', true, 49, 0, '[]'::text),
  ('김태호', '9월', true, 17, 0, '[]'::text),
  ('김하나', '9월', true, 0, 0, '[]'::text),
  ('김하연', '9월', true, 50, 0, '[{"type":"비고","hours":"0","etc":"LDC: 21시간"}]'::text),
  ('김하영', '9월', true, 72, 0, '[]'::text),
  ('김홍철', '9월', true, 0, 0, '[]'::text),
  ('김희웅', '9월', true, 76, 0, '[]'::text),
  ('김희정', '9월', true, 40, 0, '[]'::text),
  ('문경주', '9월', true, 10, 0, '[{"type":"비고","hours":"0","etc":"원격봉사: 32시간"}]'::text),
  ('문광호', '9월', true, 43, 0, '[]'::text),
  ('문정은', '9월', true, 50, 0, '[]'::text),
  ('박근미', '9월', true, 0, 0, '[]'::text),
  ('박미희', '9월', true, 57, 0, '[]'::text),
  ('박해숙', '9월', true, 50, 0, '[]'::text),
  ('박형빈', '9월', true, 84, 0, '[]'::text),
  ('손인환', '9월', true, 56, 0, '[]'::text),
  ('손지영', '9월', true, 35, 1, '[]'::text),
  ('신경옥', '9월', true, 15, 0, '[]'::text),
  ('신경희', '9월', true, 0, 0, '[]'::text),
  ('신미연', '9월', true, 0, 0, '[]'::text),
  ('심인숙', '9월', true, 68, 0, '[]'::text),
  ('안명길', '9월', true, 70, 1, '[]'::text),
  ('오경숙', '9월', true, 0, 0, '[]'::text),
  ('오규원', '9월', true, 50, 0, '[]'::text),
  ('우성제', '9월', true, 16, 0, '[]'::text),
  ('위영희', '9월', true, 58, 0, '[]'::text),
  ('이경진', '9월', true, 46, 0, '[]'::text),
  ('이경훈', '9월', true, 0, 0, '[]'::text),
  ('이기운', '9월', true, 148, 3, '[]'::text),
  ('이순금', '9월', true, 0, 0, '[]'::text),
  ('이순주', '9월', true, 55, 4, '[]'::text),
  ('이용규', '9월', true, 26, 0, '[]'::text),
  ('이은옥', '9월', true, 0, 0, '[]'::text),
  ('이재춘', '9월', true, 0, 0, '[]'::text),
  ('이정구', '9월', true, 31, 1, '[]'::text),
  ('이창희', '9월', true, 150, 2, '[]'::text),
  ('이채민', '9월', true, 0, 0, '[]'::text),
  ('이춘자', '9월', true, 0, 0, '[]'::text),
  ('이혜숙', '9월', true, 51, 0, '[]'::text),
  ('인혜진', '9월', true, 54, 1, '[]'::text),
  ('임연순', '9월', true, 65, 0, '[]'::text),
  ('임예린', '9월', true, 0, 0, '[]'::text),
  ('임윤섭', '9월', true, 83, 5, '[]'::text),
  ('장은주', '9월', true, 52, 0, '[]'::text),
  ('장지은', '9월', true, 52, 1, '[]'::text),
  ('전은아', '9월', true, 51, 0, '[]'::text),
  ('전인숙', '9월', true, 84, 2, '[]'::text),
  ('전종성', '9월', true, 54, 0, '[]'::text),
  ('전지훈', '9월', true, 54, 0, '[]'::text),
  ('전진혁', '9월', true, 15, 0, '[]'::text),
  ('전채균', '9월', true, 34, 0, '[]'::text),
  ('전호진', '9월', true, 30, 0, '[]'::text),
  ('정금석', '9월', true, 0, 0, '[]'::text),
  ('정명희', '9월', true, 0, 0, '[]'::text),
  ('정복희', '9월', true, 65, 1, '[]'::text),
  ('정승헌', '9월', true, 41, 0, '[]'::text),
  ('정태희', '9월', true, 30, 0, '[]'::text),
  ('정향순', '9월', true, 0, 0, '[]'::text),
  ('조규설', '9월', true, 0, 0, '[]'::text),
  ('조월동', '9월', true, 15, 0, '[]'::text),
  ('조인형', '9월', true, 55, 1, '[]'::text),
  ('조행진', '9월', true, 49, 0, '[]'::text),
  ('주우규', '9월', true, 67, 0, '[]'::text),
  ('진선미', '9월', true, 0, 0, '[]'::text),
  ('채영진', '9월', true, 75, 0, '[]'::text),
  ('최선율', '9월', true, 0, 0, '[]'::text),
  ('최수정', '9월', true, 0, 0, '[]'::text),
  ('최승준', '9월', true, 0, 0, '[]'::text),
  ('최현수', '9월', true, 22, 1, '[]'::text),
  ('한명숙', '9월', true, 45, 0, '[]'::text),
  ('황민숙', '9월', true, 51, 0, '[]'::text),
  ('황선영', '9월', true, 0, 0, '[]'::text),
  ('황은영', '9월', true, 0, 0, '[]'::text),
  ('강미숙', '10월', true, 0, 0, '[]'::text),
  ('강석찬', '10월', true, 56, 0, '[{"type":"비고","hours":"0","etc":"(늦게 보고)"}]'::text),
  ('강선아', '10월', true, 48, 0, '[]'::text)
) AS v(name, month, participated, hours, bible_studies, remarks)
CROSS JOIN (SELECT id FROM public.service_years WHERE year_name = '2025' LIMIT 1) sy
JOIN public.publishers p ON p.name = v.name
ON CONFLICT (service_year_id, publisher_id, month) 
DO UPDATE SET 
  participated = EXCLUDED.participated,
  hours = EXCLUDED.hours,
  bible_studies = EXCLUDED.bible_studies,
  remarks = EXCLUDED.remarks;

INSERT INTO public.monthly_reports (service_year_id, publisher_id, month, participated, hours, bible_studies, remarks, submitted_at)
SELECT 
  sy.id,
  p.id,
  v.month,
  v.participated,
  v.hours,
  v.bible_studies,
  v.remarks::JSONB,
  '2024-09-01 00:00:00+00'::TIMESTAMPTZ
FROM (VALUES
  ('강영아', '10월', true, 0, 0, '[]'::text),
  ('강정구', '10월', true, 63, 0, '[]'::text),
  ('권선', '10월', true, 51, 0, '[]'::text),
  ('김랑임', '10월', true, 50, 0, '[]'::text),
  ('김명철', '10월', true, 0, 0, '[]'::text),
  ('김미옥', '10월', true, 0, 0, '[]'::text),
  ('김상만', '10월', true, 0, 0, '[]'::text),
  ('김선혁', '10월', true, 31, 0, '[]'::text),
  ('김세나', '10월', true, 56, 1, '[]'::text),
  ('김수빈', '10월', true, 60, 0, '[]'::text),
  ('김승연', '10월', true, 42, 0, '[]'::text),
  ('김승일', '10월', true, 50, 0, '[]'::text),
  ('김영일', '10월', true, 50, 0, '[]'::text),
  ('김인자', '10월', true, 91, 4, '[]'::text),
  ('김정남', '10월', true, 53, 0, '[]'::text),
  ('김정민', '10월', true, 38, 0, '[]'::text),
  ('김정숙', '10월', true, 72, 0, '[]'::text),
  ('김주연', '10월', true, 56, 0, '[]'::text),
  ('김준', '10월', true, 29, 0, '[{"type":"비고","hours":"0","etc":"탈골"}]'::text),
  ('김지애', '10월', true, 12, 0, '[]'::text),
  ('김지영', '10월', true, 45, 0, '[{"type":"비고","hours":"0","etc":"LDC: 80시간"}]'::text),
  ('김태민', '10월', true, 45, 0, '[]'::text),
  ('김태호', '10월', true, 22, 0, '[]'::text),
  ('김하나', '10월', true, 0, 0, '[]'::text),
  ('김하연', '10월', true, 52, 0, '[]'::text),
  ('김하영', '10월', true, 61, 1, '[]'::text),
  ('김홍철', '10월', true, 0, 0, '[]'::text),
  ('김희웅', '10월', true, 79, 0, '[]'::text),
  ('김희정', '10월', true, 54, 0, '[]'::text),
  ('문경주', '10월', true, 10, 0, '[{"type":"비고","hours":"0","etc":"칠레 지역대회"}]'::text),
  ('문광호', '10월', true, 50, 0, '[]'::text),
  ('문정은', '10월', true, 50, 0, '[]'::text),
  ('박근미', '10월', true, 0, 0, '[]'::text),
  ('박미희', '10월', true, 58, 0, '[]'::text),
  ('박해숙', '10월', true, 50, 0, '[]'::text),
  ('박형빈', '10월', true, 75, 0, '[]'::text),
  ('손인환', '10월', true, 88, 0, '[]'::text),
  ('손지영', '10월', true, 32, 1, '[{"type":"비고","hours":"0","etc":"칠레 지역대회"}]'::text),
  ('신경옥', '10월', true, 15, 0, '[]'::text),
  ('신경희', '10월', true, 0, 0, '[]'::text),
  ('신미연', '10월', true, 0, 0, '[]'::text),
  ('심인숙', '10월', true, 33, 0, '[]'::text),
  ('안명길', '10월', true, 87, 1, '[]'::text),
  ('오경숙', '10월', true, 0, 0, '[]'::text),
  ('오규원', '10월', true, 50, 0, '[]'::text),
  ('우성제', '10월', true, 15, 0, '[]'::text),
  ('위영희', '10월', true, 53, 0, '[]'::text),
  ('이경진', '10월', true, 34, 0, '[{"type":"비고","hours":"0","etc":"지방출장"}]'::text),
  ('이경훈', '10월', true, 0, 0, '[]'::text),
  ('이기운', '10월', true, 76, 3, '[]'::text),
  ('이순금', '10월', true, 0, 0, '[]'::text),
  ('이순주', '10월', true, 65, 4, '[]'::text),
  ('이용규', '10월', true, 26, 0, '[]'::text),
  ('이은옥', '10월', true, 0, 0, '[]'::text),
  ('이재춘', '10월', true, 127, 0, '[]'::text),
  ('이정구', '10월', true, 37, 1, '[]'::text),
  ('이창희', '10월', true, 168, 2, '[]'::text),
  ('이채민', '10월', true, 0, 0, '[]'::text),
  ('이춘자', '10월', true, 0, 0, '[]'::text),
  ('이혜숙', '10월', true, 55, 0, '[]'::text),
  ('인혜진', '10월', true, 68, 1, '[]'::text),
  ('임연순', '10월', true, 60, 0, '[]'::text),
  ('임예린', '10월', true, 0, 0, '[]'::text),
  ('임윤섭', '10월', true, 75, 4, '[]'::text),
  ('장은주', '10월', true, 50, 0, '[]'::text),
  ('장지은', '10월', true, 51, 1, '[]'::text),
  ('전은아', '10월', true, 52, 0, '[]'::text),
  ('전인숙', '10월', true, 72, 0, '[]'::text),
  ('전종성', '10월', true, 22, 0, '[]'::text),
  ('전지훈', '10월', true, 40, 1, '[]'::text),
  ('전진혁', '10월', true, 16, 0, '[]'::text),
  ('전채균', '10월', true, 34, 0, '[]'::text),
  ('전호진', '10월', true, 32, 0, '[]'::text),
  ('정금석', '10월', true, 0, 0, '[]'::text),
  ('정명희', '10월', true, 0, 0, '[]'::text),
  ('정복희', '10월', true, 60, 1, '[]'::text),
  ('정승헌', '10월', true, 39, 0, '[]'::text),
  ('정태희', '10월', true, 0, 0, '[]'::text),
  ('정향순', '10월', true, 0, 0, '[]'::text),
  ('조규설', '10월', true, 0, 0, '[]'::text),
  ('조월동', '10월', true, 0, 0, '[]'::text),
  ('조인형', '10월', true, 62, 1, '[]'::text),
  ('조행진', '10월', true, 50, 0, '[]'::text),
  ('주우규', '10월', true, 50, 0, '[]'::text),
  ('진선미', '10월', true, 0, 0, '[]'::text),
  ('채영진', '10월', true, 69, 0, '[]'::text),
  ('최선율', '10월', true, 30, 0, '[]'::text),
  ('최수정', '10월', true, 0, 0, '[]'::text),
  ('최승준', '10월', true, 38, 0, '[]'::text),
  ('최현수', '10월', true, 32, 1, '[]'::text),
  ('한명숙', '10월', true, 44, 0, '[]'::text),
  ('황민숙', '10월', true, 33, 0, '[]'::text),
  ('황선영', '10월', true, 0, 0, '[]'::text),
  ('황은영', '10월', true, 0, 0, '[]'::text),
  ('강미숙', '11월', true, 0, 0, '[]'::text),
  ('강석찬', '11월', true, 55, 0, '[]'::text),
  ('강선아', '11월', true, 36, 0, '[]'::text),
  ('강영아', '11월', true, 0, 0, '[]'::text),
  ('강정구', '11월', true, 56, 0, '[]'::text),
  ('권선', '11월', true, 52, 0, '[]'::text)
) AS v(name, month, participated, hours, bible_studies, remarks)
CROSS JOIN (SELECT id FROM public.service_years WHERE year_name = '2025' LIMIT 1) sy
JOIN public.publishers p ON p.name = v.name
ON CONFLICT (service_year_id, publisher_id, month) 
DO UPDATE SET 
  participated = EXCLUDED.participated,
  hours = EXCLUDED.hours,
  bible_studies = EXCLUDED.bible_studies,
  remarks = EXCLUDED.remarks;

INSERT INTO public.monthly_reports (service_year_id, publisher_id, month, participated, hours, bible_studies, remarks, submitted_at)
SELECT 
  sy.id,
  p.id,
  v.month,
  v.participated,
  v.hours,
  v.bible_studies,
  v.remarks::JSONB,
  '2024-09-01 00:00:00+00'::TIMESTAMPTZ
FROM (VALUES
  ('김랑임', '11월', true, 50, 0, '[]'::text),
  ('김명철', '11월', true, 0, 0, '[]'::text),
  ('김미옥', '11월', true, 0, 0, '[]'::text),
  ('김상만', '11월', true, 0, 0, '[]'::text),
  ('김수빈', '11월', true, 36, 0, '[]'::text),
  ('김승연', '11월', true, 40, 0, '[]'::text),
  ('김승일', '11월', true, 36, 0, '[]'::text),
  ('김영일', '11월', true, 48, 0, '[]'::text),
  ('김인자', '11월', true, 94, 5, '[]'::text),
  ('김정남', '11월', true, 41, 0, '[]'::text),
  ('김정민', '11월', true, 45, 0, '[]'::text),
  ('김정숙', '11월', true, 63, 0, '[]'::text),
  ('김주연', '11월', true, 60, 0, '[]'::text),
  ('김준', '11월', true, 42, 0, '[]'::text),
  ('김지애', '11월', true, 0, 0, '[]'::text),
  ('김태민', '11월', true, 34, 0, '[]'::text),
  ('김태호', '11월', true, 0, 0, '[]'::text),
  ('김하나', '11월', true, 0, 0, '[]'::text),
  ('김하연', '11월', true, 49, 0, '[{"type":"비고","hours":"0","etc":"LDC: 28시간"}]'::text),
  ('김홍철', '11월', true, 0, 0, '[]'::text),
  ('김희웅', '11월', true, 59, 0, '[]'::text),
  ('김희정', '11월', true, 43, 0, '[]'::text),
  ('문경주', '11월', true, 35, 0, '[{"type":"비고","hours":"0","etc":"원격봉사: 30시간"}]'::text),
  ('문광호', '11월', true, 50, 0, '[]'::text),
  ('문정은', '11월', true, 46, 0, '[]'::text),
  ('박근미', '11월', true, 0, 0, '[]'::text),
  ('박미희', '11월', true, 55, 0, '[]'::text),
  ('박해숙', '11월', true, 50, 0, '[]'::text),
  ('박형빈', '11월', true, 64, 0, '[]'::text),
  ('손인환', '11월', true, 35, 0, '[]'::text),
  ('손지영', '11월', true, 101, 0, '[]'::text),
  ('신경옥', '11월', true, 0, 0, '[]'::text),
  ('신경희', '11월', true, 0, 0, '[]'::text),
  ('신미연', '11월', true, 0, 0, '[]'::text),
  ('심인숙', '11월', true, 56, 0, '[]'::text),
  ('안명길', '11월', true, 83, 1, '[]'::text),
  ('오경숙', '11월', true, 0, 0, '[]'::text),
  ('오규원', '11월', true, 50, 0, '[]'::text),
  ('우성제', '11월', true, 0, 0, '[]'::text),
  ('위영희', '11월', true, 52, 0, '[]'::text),
  ('이경진', '11월', true, 63, 0, '[]'::text),
  ('이경훈', '11월', true, 0, 0, '[]'::text),
  ('이기운', '11월', true, 75, 3, '[]'::text),
  ('이순금', '11월', true, 0, 0, '[]'::text),
  ('이순주', '11월', true, 58, 4, '[]'::text),
  ('이용규', '11월', true, 0, 0, '[]'::text),
  ('이은옥', '11월', true, 0, 0, '[]'::text),
  ('이재춘', '11월', true, 119, 0, '[]'::text),
  ('이정구', '11월', true, 32, 1, '[]'::text),
  ('이창희', '11월', true, 135, 2, '[]'::text),
  ('이채민', '11월', true, 0, 0, '[]'::text),
  ('이춘자', '11월', true, 0, 0, '[]'::text),
  ('이혜숙', '11월', true, 44, 0, '[]'::text),
  ('인혜진', '11월', true, 49, 1, '[]'::text),
  ('임연순', '11월', true, 57, 0, '[]'::text),
  ('장정자', '11월', true, 0, 0, '[]'::text),
  ('장지은', '11월', true, 40, 1, '[{"type":"비고","hours":"0","etc":"질병"}]'::text),
  ('전은아', '11월', true, 50, 0, '[]'::text),
  ('전인숙', '11월', true, 62, 0, '[]'::text),
  ('전종성', '11월', true, 8, 0, '[{"type":"비고","hours":"0","etc":"질병"}]'::text),
  ('전지훈', '11월', true, 35, 0, '[]'::text),
  ('전진혁', '11월', true, 0, 0, '[]'::text),
  ('전채균', '11월', true, 32, 0, '[]'::text),
  ('전호진', '11월', true, 30, 0, '[]'::text),
  ('정금석', '11월', true, 0, 0, '[]'::text),
  ('정명희', '11월', true, 0, 0, '[]'::text),
  ('정복희', '11월', true, 50, 1, '[]'::text),
  ('정승헌', '11월', true, 40, 0, '[]'::text),
  ('정태희', '11월', true, 0, 0, '[]'::text),
  ('정향순', '11월', true, 0, 0, '[]'::text),
  ('조규설', '11월', true, 0, 0, '[]'::text),
  ('조월동', '11월', true, 0, 0, '[]'::text),
  ('조인형', '11월', true, 52, 1, '[]'::text),
  ('조행진', '11월', true, 43, 0, '[]'::text),
  ('주우규', '11월', true, 57, 0, '[]'::text),
  ('진선미', '11월', true, 0, 0, '[]'::text),
  ('채영진', '11월', true, 65, 0, '[]'::text),
  ('최선율', '11월', true, 0, 0, '[]'::text),
  ('최수정', '11월', true, 0, 0, '[]'::text),
  ('최승준', '11월', true, 32, 0, '[]'::text),
  ('최현수', '11월', true, 0, 1, '[]'::text),
  ('한명숙', '11월', true, 33, 0, '[]'::text),
  ('황민숙', '11월', true, 41, 0, '[]'::text),
  ('황선영', '11월', true, 0, 0, '[]'::text),
  ('황은영', '11월', true, 0, 0, '[]'::text),
  ('강미숙', '12월', true, 0, 0, '[]'::text),
  ('강석찬', '12월', true, 50, 0, '[]'::text),
  ('강선아', '12월', true, 58, 0, '[]'::text),
  ('강영아', '12월', true, 0, 0, '[]'::text),
  ('강정구', '12월', true, 60, 0, '[]'::text),
  ('권선', '12월', true, 51, 0, '[]'::text),
  ('김랑임', '12월', true, 51, 0, '[]'::text),
  ('김명철', '12월', true, 0, 0, '[]'::text),
  ('김미옥', '12월', true, 0, 0, '[]'::text),
  ('김상만', '12월', true, 0, 0, '[]'::text),
  ('김수빈', '12월', true, 45, 0, '[]'::text),
  ('김승연', '12월', true, 42, 0, '[]'::text),
  ('김승일', '12월', true, 52, 1, '[{"type":"비고","hours":"0","etc":"순특공: 10시간"}]'::text),
  ('김영일', '12월', true, 48, 0, '[]'::text),
  ('김인자', '12월', true, 74, 5, '[]'::text)
) AS v(name, month, participated, hours, bible_studies, remarks)
CROSS JOIN (SELECT id FROM public.service_years WHERE year_name = '2025' LIMIT 1) sy
JOIN public.publishers p ON p.name = v.name
ON CONFLICT (service_year_id, publisher_id, month) 
DO UPDATE SET 
  participated = EXCLUDED.participated,
  hours = EXCLUDED.hours,
  bible_studies = EXCLUDED.bible_studies,
  remarks = EXCLUDED.remarks;

INSERT INTO public.monthly_reports (service_year_id, publisher_id, month, participated, hours, bible_studies, remarks, submitted_at)
SELECT 
  sy.id,
  p.id,
  v.month,
  v.participated,
  v.hours,
  v.bible_studies,
  v.remarks::JSONB,
  '2024-09-01 00:00:00+00'::TIMESTAMPTZ
FROM (VALUES
  ('김정남', '12월', true, 52, 0, '[]'::text),
  ('김정민', '12월', true, 48, 0, '[]'::text),
  ('김정숙', '12월', true, 86, 0, '[]'::text),
  ('김주연', '12월', true, 48, 0, '[]'::text),
  ('김준', '12월', true, 55, 0, '[]'::text),
  ('김지애', '12월', true, 0, 0, '[]'::text),
  ('김태민', '12월', true, 67, 0, '[]'::text),
  ('김태호', '12월', true, 0, 0, '[]'::text),
  ('김하나', '12월', true, 0, 0, '[]'::text),
  ('김하연', '12월', true, 69, 0, '[]'::text),
  ('김홍철', '12월', true, 0, 0, '[]'::text),
  ('김희웅', '12월', true, 70, 0, '[]'::text),
  ('김희정', '12월', true, 51, 0, '[]'::text),
  ('문경주', '12월', true, 35, 0, '[{"type":"비고","hours":"0","etc":"원격봉사: 48시간"}]'::text),
  ('문광호', '12월', true, 57, 0, '[]'::text),
  ('문정은', '12월', true, 50, 0, '[]'::text),
  ('박근미', '12월', true, 0, 0, '[]'::text),
  ('박미희', '12월', true, 54, 0, '[]'::text),
  ('박해숙', '12월', true, 50, 0, '[]'::text),
  ('박형빈', '12월', true, 74, 0, '[]'::text),
  ('손인환', '12월', true, 42, 0, '[{"type":"비고","hours":"0","etc":"LDC: 8시간"}]'::text),
  ('손지영', '12월', true, 65, 1, '[]'::text),
  ('신경옥', '12월', true, 0, 0, '[]'::text),
  ('신경희', '12월', true, 0, 0, '[]'::text),
  ('신미연', '12월', true, 0, 0, '[]'::text),
  ('심인숙', '12월', true, 88, 0, '[]'::text),
  ('안명길', '12월', true, 77, 1, '[]'::text),
  ('오경숙', '12월', true, 0, 0, '[]'::text),
  ('오규원', '12월', true, 50, 0, '[]'::text),
  ('우성제', '12월', true, 0, 0, '[]'::text),
  ('위영희', '12월', true, 51, 0, '[]'::text),
  ('이경진', '12월', true, 46, 0, '[]'::text),
  ('이경훈', '12월', true, 0, 0, '[]'::text),
  ('이기운', '12월', true, 49, 3, '[]'::text),
  ('이순금', '12월', true, 0, 0, '[]'::text),
  ('이순주', '12월', true, 55, 4, '[]'::text),
  ('이용규', '12월', true, 0, 0, '[]'::text),
  ('이은옥', '12월', true, 0, 0, '[]'::text),
  ('이재춘', '12월', true, 106, 0, '[]'::text),
  ('이정구', '12월', true, 34, 1, '[]'::text),
  ('이창희', '12월', true, 169, 2, '[]'::text),
  ('이채민', '12월', true, 0, 0, '[]'::text),
  ('이춘자', '12월', true, 0, 0, '[]'::text),
  ('이혜숙', '12월', true, 37, 0, '[]'::text),
  ('인혜진', '12월', true, 53, 1, '[]'::text),
  ('임연순', '12월', true, 55, 0, '[]'::text),
  ('장정자', '12월', true, 0, 0, '[]'::text),
  ('장지은', '12월', true, 65, 1, '[]'::text),
  ('전은아', '12월', true, 50, 0, '[]'::text),
  ('전인숙', '12월', true, 48, 2, '[]'::text),
  ('전지훈', '12월', true, 45, 1, '[]'::text),
  ('전진혁', '12월', true, 0, 0, '[]'::text),
  ('전채균', '12월', true, 0, 0, '[]'::text),
  ('전호진', '12월', true, 50, 0, '[{"type":"비고","hours":"0","etc":"정규 시작"}]'::text),
  ('정금석', '12월', true, 0, 0, '[]'::text),
  ('정명희', '12월', true, 0, 0, '[]'::text),
  ('정복희', '12월', true, 50, 1, '[]'::text),
  ('정승헌', '12월', true, 41, 0, '[]'::text),
  ('정태희', '12월', true, 0, 0, '[]'::text),
  ('정향순', '12월', true, 0, 0, '[]'::text),
  ('조규설', '12월', true, 0, 0, '[]'::text),
  ('조월동', '12월', true, 30, 0, '[]'::text),
  ('조인형', '12월', true, 51, 0, '[]'::text),
  ('조행진', '12월', true, 42, 0, '[]'::text),
  ('주우규', '12월', true, 60, 0, '[]'::text),
  ('진선미', '12월', true, 0, 0, '[]'::text),
  ('채영진', '12월', true, 69, 0, '[]'::text),
  ('최선율', '12월', true, 0, 0, '[]'::text),
  ('최수정', '12월', true, 0, 0, '[]'::text),
  ('최승준', '12월', true, 30, 0, '[]'::text),
  ('최현수', '12월', true, 0, 2, '[]'::text),
  ('한명숙', '12월', true, 35, 0, '[]'::text),
  ('황선영', '12월', true, 0, 0, '[]'::text),
  ('황은영', '12월', true, 0, 0, '[]'::text),
  ('강미숙', '1월', true, 0, 0, '[]'::text),
  ('강석찬', '1월', true, 46, 0, '[]'::text),
  ('강선아', '1월', true, 51, 0, '[]'::text),
  ('강영아', '1월', true, 0, 0, '[]'::text),
  ('강정구', '1월', true, 63, 0, '[]'::text),
  ('권선', '1월', true, 50, 0, '[]'::text),
  ('김랑임', '1월', true, 20, 0, '[]'::text),
  ('김명철', '1월', true, 0, 0, '[]'::text),
  ('김미옥', '1월', true, 0, 0, '[]'::text),
  ('김상만', '1월', true, 0, 0, '[]'::text),
  ('김수빈', '1월', true, 40, 0, '[]'::text),
  ('김승연', '1월', true, 36, 0, '[]'::text),
  ('김승일', '1월', true, 50, 1, '[{"type":"비고","hours":"0","etc":"순특공: 10시간"}]'::text),
  ('김영일', '1월', true, 25, 0, '[]'::text),
  ('김인자', '1월', true, 51, 3, '[]'::text),
  ('김정남', '1월', true, 50, 0, '[]'::text),
  ('김정민', '1월', true, 40, 1, '[]'::text),
  ('김정숙', '1월', true, 41, 0, '[]'::text),
  ('김주연', '1월', true, 50, 0, '[]'::text),
  ('김준', '1월', true, 30, 0, '[]'::text),
  ('김지애', '1월', true, 0, 0, '[]'::text),
  ('김태민', '1월', true, 47, 0, '[]'::text),
  ('김태호', '1월', true, 0, 0, '[]'::text),
  ('김하나', '1월', true, 0, 0, '[]'::text),
  ('김하연', '1월', true, 42, 0, '[{"type":"비고","hours":"0","etc":"LDC: 63시간"}]'::text),
  ('김홍철', '1월', true, 0, 0, '[]'::text)
) AS v(name, month, participated, hours, bible_studies, remarks)
CROSS JOIN (SELECT id FROM public.service_years WHERE year_name = '2025' LIMIT 1) sy
JOIN public.publishers p ON p.name = v.name
ON CONFLICT (service_year_id, publisher_id, month) 
DO UPDATE SET 
  participated = EXCLUDED.participated,
  hours = EXCLUDED.hours,
  bible_studies = EXCLUDED.bible_studies,
  remarks = EXCLUDED.remarks;

INSERT INTO public.monthly_reports (service_year_id, publisher_id, month, participated, hours, bible_studies, remarks, submitted_at)
SELECT 
  sy.id,
  p.id,
  v.month,
  v.participated,
  v.hours,
  v.bible_studies,
  v.remarks::JSONB,
  '2024-09-01 00:00:00+00'::TIMESTAMPTZ
FROM (VALUES
  ('김희웅', '1월', true, 62, 0, '[]'::text),
  ('김희정', '1월', true, 30, 0, '[]'::text),
  ('문경주', '1월', true, 35, 0, '[{"type":"비고","hours":"0","etc":"원격봉사,LDC: 61시간"}]'::text),
  ('문광호', '1월', true, 45, 0, '[]'::text),
  ('문정은', '1월', true, 45, 0, '[]'::text),
  ('박근미', '1월', true, 0, 0, '[]'::text),
  ('박미희', '1월', true, 55, 0, '[]'::text),
  ('박해숙', '1월', true, 50, 0, '[]'::text),
  ('박형빈', '1월', true, 70, 0, '[]'::text),
  ('손지영', '1월', true, 64, 0, '[{"type":"비고","hours":"0","etc":"LDC: 16시간"}]'::text),
  ('신경옥', '1월', true, 0, 0, '[]'::text),
  ('신경희', '1월', true, 0, 0, '[]'::text),
  ('신미연', '1월', true, 0, 0, '[]'::text),
  ('심인숙', '1월', true, 78, 0, '[]'::text),
  ('안명길', '1월', true, 66, 1, '[]'::text),
  ('오경숙', '1월', true, 0, 0, '[]'::text),
  ('오규원', '1월', true, 50, 0, '[]'::text),
  ('우성제', '1월', true, 0, 0, '[]'::text),
  ('위영희', '1월', true, 51, 0, '[]'::text),
  ('이경진', '1월', true, 50, 0, '[]'::text),
  ('이경훈', '1월', true, 0, 0, '[]'::text),
  ('이기운', '1월', true, 36, 2, '[]'::text),
  ('이순금', '1월', true, 0, 0, '[]'::text),
  ('이순주', '1월', true, 71, 4, '[]'::text),
  ('이용규', '1월', true, 0, 0, '[]'::text),
  ('이은옥', '1월', true, 0, 0, '[]'::text),
  ('이재춘', '1월', true, 90, 0, '[]'::text),
  ('이정구', '1월', true, 0, 1, '[]'::text),
  ('이창희', '1월', true, 94, 1, '[]'::text),
  ('이채민', '1월', true, 0, 0, '[]'::text),
  ('이춘자', '1월', true, 0, 0, '[]'::text),
  ('이혜숙', '1월', true, 42, 0, '[]'::text),
  ('인혜진', '1월', true, 57, 1, '[]'::text),
  ('임연순', '1월', true, 52, 0, '[]'::text),
  ('장정자', '1월', true, 0, 0, '[]'::text),
  ('장지은', '1월', true, 50, 1, '[]'::text),
  ('전은아', '1월', true, 51, 1, '[]'::text),
  ('전인숙', '1월', true, 64, 1, '[]'::text),
  ('전지훈', '1월', true, 52, 0, '[]'::text),
  ('전진혁', '1월', true, 0, 0, '[]'::text),
  ('전채균', '1월', true, 0, 0, '[]'::text),
  ('전호진', '1월', true, 42, 0, '[]'::text),
  ('정금석', '1월', true, 0, 0, '[]'::text),
  ('정명희', '1월', true, 0, 0, '[]'::text),
  ('정복희', '1월', true, 50, 0, '[]'::text),
  ('정승헌', '1월', true, 42, 0, '[]'::text),
  ('정태희', '1월', true, 40, 0, '[]'::text),
  ('정향순', '1월', true, 0, 0, '[]'::text),
  ('조규설', '1월', true, 0, 0, '[{"type":"비고","hours":"0","etc":"사망"}]'::text),
  ('조월동', '1월', true, 30, 0, '[]'::text),
  ('조인형', '1월', true, 54, 0, '[]'::text),
  ('조행진', '1월', true, 50, 0, '[]'::text),
  ('주우규', '1월', true, 61, 0, '[]'::text),
  ('진선미', '1월', true, 0, 0, '[]'::text),
  ('채영진', '1월', true, 60, 0, '[]'::text),
  ('최선율', '1월', true, 40, 0, '[]'::text),
  ('최수정', '1월', true, 0, 0, '[]'::text),
  ('최승준', '1월', true, 53, 0, '[]'::text),
  ('최현수', '1월', true, 37, 1, '[]'::text),
  ('한명숙', '1월', true, 23, 1, '[]'::text),
  ('황선영', '1월', true, 0, 0, '[]'::text),
  ('황은영', '1월', true, 0, 0, '[]'::text),
  ('강미숙', '2월', true, 0, 0, '[]'::text),
  ('강석찬', '2월', true, 42, 0, '[]'::text),
  ('강선아', '2월', true, 34, 0, '[]'::text),
  ('강영아', '2월', true, 0, 0, '[]'::text),
  ('강정구', '2월', true, 62, 0, '[]'::text),
  ('권선', '2월', true, 57, 0, '[]'::text),
  ('권윤', '2월', true, 48, 0, '[]'::text),
  ('김랑임', '2월', true, 0, 0, '[]'::text),
  ('김명철', '2월', true, 0, 0, '[]'::text),
  ('김명희', '2월', true, 48, 0, '[{"type":"비고","hours":"0","etc":"전입"}]'::text),
  ('김미옥', '2월', true, 0, 0, '[]'::text),
  ('김상만', '2월', true, 0, 0, '[]'::text),
  ('김승연', '2월', true, 30, 0, '[]'::text),
  ('김승일', '2월', true, 42, 1, '[]'::text),
  ('김영일', '2월', true, 22, 0, '[]'::text),
  ('김인자', '2월', true, 63, 3, '[]'::text),
  ('김정남', '2월', true, 50, 0, '[]'::text),
  ('김정민', '2월', true, 42, 1, '[]'::text),
  ('김정숙', '2월', true, 70, 0, '[]'::text),
  ('김주연', '2월', true, 42, 0, '[{"type":"비고","hours":"0","etc":"베델초대"}]'::text),
  ('김준', '2월', true, 36, 0, '[]'::text),
  ('김지애', '2월', true, 0, 0, '[]'::text),
  ('김태민', '2월', true, 46, 0, '[]'::text),
  ('김태호', '2월', true, 0, 0, '[]'::text),
  ('김하나', '2월', true, 0, 0, '[]'::text),
  ('김하연', '2월', true, 55, 0, '[]'::text),
  ('김홍철', '2월', true, 0, 0, '[]'::text),
  ('김희웅', '2월', true, 72, 0, '[]'::text),
  ('김희정', '2월', true, 50, 0, '[]'::text),
  ('문경주', '2월', true, 35, 0, '[{"type":"비고","hours":"0","etc":"원격봉사: 48시간"}]'::text),
  ('문광호', '2월', true, 47, 0, '[]'::text),
  ('문정은', '2월', true, 50, 0, '[]'::text),
  ('박근미', '2월', true, 0, 0, '[]'::text),
  ('박미희', '2월', true, 46, 0, '[]'::text),
  ('박해숙', '2월', true, 50, 0, '[]'::text),
  ('박형빈', '2월', true, 59, 0, '[]'::text),
  ('손지영', '2월', true, 42, 1, '[]'::text),
  ('신경옥', '2월', true, 0, 0, '[]'::text)
) AS v(name, month, participated, hours, bible_studies, remarks)
CROSS JOIN (SELECT id FROM public.service_years WHERE year_name = '2025' LIMIT 1) sy
JOIN public.publishers p ON p.name = v.name
ON CONFLICT (service_year_id, publisher_id, month) 
DO UPDATE SET 
  participated = EXCLUDED.participated,
  hours = EXCLUDED.hours,
  bible_studies = EXCLUDED.bible_studies,
  remarks = EXCLUDED.remarks;

INSERT INTO public.monthly_reports (service_year_id, publisher_id, month, participated, hours, bible_studies, remarks, submitted_at)
SELECT 
  sy.id,
  p.id,
  v.month,
  v.participated,
  v.hours,
  v.bible_studies,
  v.remarks::JSONB,
  '2024-09-01 00:00:00+00'::TIMESTAMPTZ
FROM (VALUES
  ('신경희', '2월', true, 0, 0, '[]'::text),
  ('신미연', '2월', true, 0, 0, '[]'::text),
  ('신범선', '2월', true, 48, 1, '[{"type":"비고","hours":"0","etc":"전입"}]'::text),
  ('심인숙', '2월', true, 71, 0, '[]'::text),
  ('안명길', '2월', true, 58, 1, '[]'::text),
  ('오경숙', '2월', true, 0, 0, '[]'::text),
  ('우성제', '2월', true, 0, 0, '[]'::text),
  ('위영희', '2월', true, 37, 0, '[]'::text),
  ('이경진', '2월', true, 53, 0, '[]'::text),
  ('이경훈', '2월', true, 0, 0, '[]'::text),
  ('이기운', '2월', true, 0, 2, '[]'::text),
  ('이순금', '2월', true, 0, 0, '[]'::text),
  ('이순주', '2월', true, 61, 4, '[]'::text),
  ('이슬아', '2월', true, 50, 0, '[{"type":"비고","hours":"0","etc":"전입"}]'::text),
  ('이용규', '2월', true, 0, 0, '[]'::text),
  ('이은옥', '2월', true, 0, 0, '[]'::text),
  ('이재춘', '2월', true, 83, 0, '[]'::text),
  ('이정구', '2월', true, 0, 0, '[]'::text),
  ('이정인', '2월', true, 42, 1, '[{"type":"비고","hours":"0","etc":"전입"}]'::text),
  ('이창희', '2월', true, 104, 2, '[]'::text),
  ('이채민', '2월', true, 0, 0, '[]'::text),
  ('이춘자', '2월', true, 0, 0, '[]'::text),
  ('이혜미', '2월', true, 42, 2, '[{"type":"비고","hours":"0","etc":"전입"}]'::text),
  ('이혜숙', '2월', true, 42, 0, '[]'::text),
  ('인혜진', '2월', true, 50, 1, '[]'::text),
  ('임연순', '2월', true, 47, 0, '[]'::text),
  ('장정자', '2월', true, 0, 0, '[]'::text),
  ('장지은', '2월', true, 50, 0, '[]'::text),
  ('전은아', '2월', true, 45, 1, '[]'::text),
  ('전인숙', '2월', true, 61, 2, '[]'::text),
  ('전재관', '2월', true, 48, 2, '[{"type":"비고","hours":"0","etc":"전입"}]'::text),
  ('전지훈', '2월', true, 47, 1, '[]'::text),
  ('전진혁', '2월', true, 0, 0, '[]'::text),
  ('전채균', '2월', true, 0, 0, '[]'::text),
  ('전혜인', '2월', true, 37, 1, '[{"type":"비고","hours":"0","etc":"전입"}]'::text),
  ('전호진', '2월', true, 40, 0, '[]'::text),
  ('정금석', '2월', true, 0, 0, '[]'::text),
  ('정명희', '2월', true, 0, 0, '[]'::text),
  ('정복희', '2월', true, 53, 0, '[]'::text),
  ('정승헌', '2월', true, 38, 0, '[]'::text),
  ('정태희', '2월', true, 52, 0, '[]'::text),
  ('정향순', '2월', true, 0, 0, '[]'::text),
  ('조월동', '2월', true, 0, 0, '[]'::text),
  ('조인형', '2월', true, 53, 0, '[]'::text),
  ('조행진', '2월', true, 47, 0, '[]'::text),
  ('주우규', '2월', true, 55, 0, '[]'::text),
  ('진선미', '2월', true, 0, 0, '[]'::text),
  ('채영진', '2월', true, 52, 0, '[]'::text),
  ('최선율', '2월', true, 0, 0, '[]'::text),
  ('최수정', '2월', true, 0, 0, '[]'::text),
  ('최승준', '2월', true, 53, 3, '[{"type":"비고","hours":"0","etc":"정규 시작"}]'::text),
  ('최현수', '2월', true, 0, 1, '[]'::text),
  ('한명숙', '2월', true, 26, 1, '[]'::text),
  ('허율', '2월', true, 0, 0, '[{"type":"비고","hours":"0","etc":"전입"}]'::text),
  ('황선영', '2월', true, 0, 0, '[]'::text),
  ('황은영', '2월', true, 0, 0, '[]'::text),
  ('강미숙', '3월', true, 0, 0, '[]'::text),
  ('강석찬', '3월', true, 33, 0, '[]'::text),
  ('강선아', '3월', true, 39, 0, '[{"type":"비고","hours":"0","etc":"LDC: 8시간"}]'::text),
  ('강영아', '3월', true, 0, 0, '[]'::text),
  ('강정구', '3월', true, 63, 0, '[]'::text),
  ('권선', '3월', true, 50, 0, '[]'::text),
  ('권윤', '3월', true, 50, 0, '[]'::text),
  ('김랑임', '3월', true, 0, 0, '[]'::text),
  ('김명철', '3월', true, 30, 0, '[]'::text),
  ('김명희', '3월', true, 57, 0, '[]'::text),
  ('김미옥', '3월', true, 0, 0, '[]'::text),
  ('김상만', '3월', true, 0, 1, '[]'::text),
  ('김승연', '3월', true, 31, 0, '[]'::text),
  ('김승일', '3월', true, 40, 1, '[{"type":"비고","hours":"0","etc":"LDC: 16시간"}]'::text),
  ('김인자', '3월', true, 77, 1, '[]'::text),
  ('김정남', '3월', true, 50, 0, '[]'::text),
  ('김정민', '3월', true, 41, 1, '[]'::text),
  ('김정숙', '3월', true, 40, 0, '[]'::text),
  ('김주연', '3월', true, 50, 0, '[]'::text),
  ('김준', '3월', true, 57, 0, '[]'::text),
  ('김지애', '3월', true, 0, 0, '[]'::text),
  ('김태민', '3월', true, 24, 0, '[]'::text),
  ('김태호', '3월', true, 16, 0, '[]'::text),
  ('김하나', '3월', true, 0, 0, '[]'::text),
  ('김하연', '3월', true, 50, 0, '[]'::text),
  ('김홍철', '3월', true, 0, 0, '[]'::text),
  ('김희웅', '3월', true, 64, 0, '[]'::text),
  ('김희정', '3월', true, 46, 0, '[]'::text),
  ('문경주', '3월', true, 35, 1, '[{"type":"비고","hours":"0","etc":"원격봉사: 35시간, LDC: 16시간"}]'::text),
  ('문광호', '3월', true, 45, 0, '[]'::text),
  ('문정은', '3월', true, 50, 0, '[]'::text),
  ('박근미', '3월', true, 0, 0, '[]'::text),
  ('박미희', '3월', true, 52, 0, '[]'::text),
  ('박해숙', '3월', true, 50, 0, '[]'::text),
  ('박형빈', '3월', true, 83, 0, '[]'::text),
  ('손지영', '3월', true, 30, 1, '[]'::text),
  ('신경희', '3월', true, 0, 0, '[]'::text),
  ('신미연', '3월', true, 0, 0, '[]'::text),
  ('신범선', '3월', true, 57, 1, '[]'::text),
  ('심인숙', '3월', true, 54, 0, '[]'::text),
  ('안명길', '3월', true, 51, 1, '[]'::text),
  ('오경숙', '3월', true, 0, 0, '[]'::text),
  ('우성제', '3월', true, 0, 0, '[]'::text),
  ('위영희', '3월', true, 55, 0, '[]'::text)
) AS v(name, month, participated, hours, bible_studies, remarks)
CROSS JOIN (SELECT id FROM public.service_years WHERE year_name = '2025' LIMIT 1) sy
JOIN public.publishers p ON p.name = v.name
ON CONFLICT (service_year_id, publisher_id, month) 
DO UPDATE SET 
  participated = EXCLUDED.participated,
  hours = EXCLUDED.hours,
  bible_studies = EXCLUDED.bible_studies,
  remarks = EXCLUDED.remarks;

INSERT INTO public.monthly_reports (service_year_id, publisher_id, month, participated, hours, bible_studies, remarks, submitted_at)
SELECT 
  sy.id,
  p.id,
  v.month,
  v.participated,
  v.hours,
  v.bible_studies,
  v.remarks::JSONB,
  '2024-09-01 00:00:00+00'::TIMESTAMPTZ
FROM (VALUES
  ('이경진', '3월', true, 46, 0, '[]'::text),
  ('이경훈', '3월', true, 19, 0, '[]'::text),
  ('이기운', '3월', true, 56, 1, '[]'::text),
  ('이순금', '3월', true, 0, 0, '[]'::text),
  ('이순주', '3월', true, 54, 3, '[{"type":"비고","hours":"0","etc":"LDC: 8시간"}]'::text),
  ('이슬아', '3월', true, 51, 0, '[{"type":"비고","hours":"0","etc":"대회사전준비: 8시간"}]'::text),
  ('이용규', '3월', true, 18, 0, '[]'::text),
  ('이은옥', '3월', true, 0, 0, '[]'::text),
  ('이재춘', '3월', true, 102, 0, '[]'::text),
  ('이정구', '3월', true, 22, 1, '[]'::text),
  ('이정인', '3월', true, 47, 1, '[{"type":"비고","hours":"0","etc":"대회사전준비: 8시간"}]'::text),
  ('이창희', '3월', true, 70, 2, '[]'::text),
  ('이채민', '3월', true, 0, 0, '[]'::text),
  ('이춘자', '3월', true, 0, 0, '[]'::text),
  ('이혜미', '3월', true, 76, 2, '[]'::text),
  ('이혜숙', '3월', true, 57, 0, '[]'::text),
  ('인혜진', '3월', true, 55, 1, '[]'::text),
  ('임연순', '3월', true, 51, 0, '[]'::text),
  ('장정자', '3월', true, 0, 0, '[]'::text),
  ('장지은', '3월', true, 42, 1, '[{"type":"비고","hours":"0","etc":"LDC: 8시간"}]'::text),
  ('전은아', '3월', true, 50, 1, '[]'::text),
  ('전인숙', '3월', true, 74, 2, '[]'::text),
  ('전재관', '3월', true, 65, 3, '[]'::text),
  ('전지훈', '3월', true, 43, 1, '[]'::text),
  ('전진혁', '3월', true, 0, 0, '[]'::text),
  ('전채균', '3월', true, 0, 0, '[]'::text),
  ('전혜인', '3월', true, 50, 1, '[]'::text),
  ('전호진', '3월', true, 53, 0, '[]'::text),
  ('정금석', '3월', true, 0, 0, '[]'::text),
  ('정명희', '3월', true, 0, 0, '[]'::text),
  ('정복희', '3월', true, 50, 0, '[]'::text),
  ('정승헌', '3월', true, 38, 0, '[]'::text),
  ('정태희', '3월', true, 42, 0, '[]'::text),
  ('정향순', '3월', true, 0, 0, '[]'::text),
  ('조월동', '3월', true, 0, 0, '[]'::text),
  ('조인형', '3월', true, 50, 0, '[{"type":"비고","hours":"0","etc":"LDC: 8시간"}]'::text),
  ('조행진', '3월', true, 42, 0, '[]'::text),
  ('주우규', '3월', true, 55, 0, '[]'::text),
  ('진선미', '3월', true, 0, 0, '[]'::text),
  ('채영진', '3월', true, 55, 0, '[]'::text),
  ('최선율', '3월', true, 15, 0, '[]'::text),
  ('최수정', '3월', true, 0, 0, '[]'::text),
  ('최승준', '3월', true, 47, 4, '[{"type":"비고","hours":"0","etc":"LDC: 16시간, 대회사전준비: 8시간"}]'::text),
  ('최현수', '3월', true, 35, 0, '[]'::text),
  ('한명숙', '3월', true, 34, 1, '[]'::text),
  ('허율', '3월', true, 0, 0, '[]'::text),
  ('황선영', '3월', true, 0, 0, '[]'::text),
  ('황은영', '3월', true, 0, 0, '[]'::text),
  ('강미숙', '4월', true, 0, 0, '[]'::text),
  ('강석찬', '4월', true, 37, 0, '[]'::text),
  ('강선아', '4월', true, 41, 0, '[]'::text),
  ('강영아', '4월', true, 0, 0, '[]'::text),
  ('강정구', '4월', true, 73, 0, '[]'::text),
  ('권선', '4월', true, 54, 0, '[]'::text),
  ('권윤', '4월', true, 50, 0, '[]'::text),
  ('김랑임', '4월', true, 0, 0, '[]'::text),
  ('김명철', '4월', true, 31, 0, '[]'::text),
  ('김명희', '4월', true, 61, 0, '[]'::text),
  ('김미옥', '4월', true, 0, 0, '[]'::text),
  ('김상만', '4월', true, 0, 1, '[]'::text),
  ('김승연', '4월', true, 32, 0, '[]'::text),
  ('김승일', '4월', true, 40, 1, '[{"type":"비고","hours":"0","etc":"순특공: 10시간"}]'::text),
  ('김인자', '4월', true, 86, 3, '[]'::text),
  ('김정남', '4월', true, 50, 0, '[]'::text),
  ('김정민', '4월', true, 44, 1, '[]'::text),
  ('김정숙', '4월', true, 55, 0, '[]'::text),
  ('김주연', '4월', true, 30, 0, '[{"type":"비고","hours":"0","etc":"베델봉사: 55시간"}]'::text),
  ('김준', '4월', true, 35, 0, '[]'::text),
  ('김지애', '4월', true, 0, 0, '[]'::text),
  ('김태민', '4월', true, 38, 0, '[]'::text),
  ('김태호', '4월', true, 15, 0, '[]'::text),
  ('김하나', '4월', true, 15, 0, '[]'::text),
  ('김하연', '4월', true, 42, 0, '[{"type":"비고","hours":"0","etc":"LDC: 7시간"}]'::text),
  ('김홍철', '4월', true, 0, 0, '[]'::text),
  ('김희웅', '4월', true, 58, 0, '[]'::text),
  ('김희정', '4월', true, 52, 0, '[]'::text),
  ('문경주', '4월', true, 28, 0, '[{"type":"비고","hours":"0","etc":"원격봉사: 25시간"}]'::text),
  ('문광호', '4월', true, 51, 0, '[]'::text),
  ('문정은', '4월', true, 50, 0, '[]'::text),
  ('박근미', '4월', true, 0, 0, '[]'::text),
  ('박미희', '4월', true, 57, 0, '[]'::text),
  ('박해숙', '4월', true, 50, 0, '[]'::text),
  ('박형빈', '4월', true, 87, 0, '[]'::text),
  ('손지영', '4월', true, 59, 1, '[]'::text),
  ('신경희', '4월', true, 0, 0, '[]'::text),
  ('신미연', '4월', true, 0, 0, '[{"type":"비고","hours":"0","etc":"2시간"}]'::text),
  ('신범선', '4월', true, 61, 1, '[]'::text),
  ('심인숙', '4월', true, 40, 0, '[]'::text),
  ('안명길', '4월', true, 50, 0, '[]'::text),
  ('오경숙', '4월', true, 0, 0, '[]'::text),
  ('우성제', '4월', true, 15, 0, '[]'::text),
  ('위영희', '4월', true, 51, 0, '[]'::text),
  ('이경진', '4월', true, 48, 0, '[]'::text),
  ('이경훈', '4월', true, 32, 0, '[]'::text),
  ('이기운', '4월', true, 100, 1, '[]'::text),
  ('이순금', '4월', true, 0, 0, '[]'::text),
  ('이순주', '4월', true, 58, 3, '[]'::text),
  ('이슬아', '4월', true, 51, 0, '[]'::text),
  ('이용규', '4월', true, 18, 0, '[]'::text),
  ('이은옥', '4월', true, 0, 0, '[]'::text)
) AS v(name, month, participated, hours, bible_studies, remarks)
CROSS JOIN (SELECT id FROM public.service_years WHERE year_name = '2025' LIMIT 1) sy
JOIN public.publishers p ON p.name = v.name
ON CONFLICT (service_year_id, publisher_id, month) 
DO UPDATE SET 
  participated = EXCLUDED.participated,
  hours = EXCLUDED.hours,
  bible_studies = EXCLUDED.bible_studies,
  remarks = EXCLUDED.remarks;

INSERT INTO public.monthly_reports (service_year_id, publisher_id, month, participated, hours, bible_studies, remarks, submitted_at)
SELECT 
  sy.id,
  p.id,
  v.month,
  v.participated,
  v.hours,
  v.bible_studies,
  v.remarks::JSONB,
  '2024-09-01 00:00:00+00'::TIMESTAMPTZ
FROM (VALUES
  ('이재춘', '4월', true, 0, 0, '[]'::text),
  ('이정구', '4월', true, 31, 1, '[]'::text),
  ('이정인', '4월', true, 55, 1, '[]'::text),
  ('이창희', '4월', true, 116, 3, '[]'::text),
  ('이채민', '4월', true, 0, 0, '[]'::text),
  ('이춘자', '4월', true, 0, 0, '[]'::text),
  ('이혜미', '4월', true, 76, 2, '[]'::text),
  ('이혜숙', '4월', true, 56, 0, '[]'::text),
  ('인혜진', '4월', true, 54, 1, '[]'::text),
  ('임연순', '4월', true, 50, 0, '[]'::text),
  ('장정자', '4월', true, 0, 0, '[]'::text),
  ('장지은', '4월', true, 50, 1, '[]'::text),
  ('전은아', '4월', true, 46, 1, '[]'::text),
  ('전인숙', '4월', true, 63, 2, '[]'::text),
  ('전재관', '4월', true, 75, 3, '[]'::text),
  ('전지훈', '4월', true, 54, 1, '[]'::text),
  ('전진혁', '4월', true, 16, 0, '[]'::text),
  ('전채균', '4월', true, 19, 0, '[]'::text),
  ('전혜인', '4월', true, 52, 1, '[]'::text),
  ('전호진', '4월', true, 42, 0, '[]'::text),
  ('정금석', '4월', true, 0, 0, '[]'::text),
  ('정명희', '4월', true, 0, 0, '[]'::text),
  ('정복희', '4월', true, 50, 0, '[]'::text),
  ('정승헌', '4월', true, 41, 0, '[]'::text),
  ('정태희', '4월', true, 56, 0, '[]'::text),
  ('정향순', '4월', true, 0, 0, '[]'::text),
  ('조월동', '4월', true, 15, 0, '[]'::text),
  ('조인형', '4월', true, 58, 1, '[]'::text),
  ('조행진', '4월', true, 34, 0, '[]'::text),
  ('주우규', '4월', true, 70, 0, '[]'::text),
  ('진선미', '4월', true, 0, 0, '[]'::text),
  ('채영진', '4월', true, 55, 0, '[]'::text),
  ('최선율', '4월', true, 17, 0, '[]'::text),
  ('최수정', '4월', true, 0, 0, '[]'::text),
  ('최승준', '4월', true, 67, 4, '[]'::text),
  ('최현수', '4월', true, 31, 1, '[]'::text),
  ('한명숙', '4월', true, 32, 1, '[]'::text),
  ('허율', '4월', true, 0, 0, '[{"type":"비고","hours":"0","etc":"편지봉사: 2시간"}]'::text),
  ('황선영', '4월', true, 0, 0, '[]'::text),
  ('황은영', '4월', true, 0, 0, '[]'::text),
  ('강미숙', '5월', true, 0, 0, '[]'::text),
  ('강석찬', '5월', true, 29, 0, '[]'::text),
  ('강선아', '5월', true, 32, 0, '[]'::text),
  ('강영아', '5월', true, 0, 0, '[]'::text),
  ('강정구', '5월', true, 39, 0, '[]'::text),
  ('권선', '5월', true, 56, 0, '[]'::text),
  ('권윤', '5월', true, 50, 0, '[]'::text),
  ('김기림', '5월', true, 46, 0, '[{"type":"비고","hours":"0","etc":"전입"}]'::text),
  ('김랑임', '5월', true, 0, 0, '[]'::text),
  ('김명철', '5월', true, 0, 0, '[]'::text),
  ('김명희', '5월', true, 52, 1, '[]'::text),
  ('김미옥', '5월', true, 0, 0, '[]'::text),
  ('김상만', '5월', true, 0, 0, '[]'::text),
  ('김승연', '5월', true, 37, 0, '[]'::text),
  ('김승일', '5월', true, 45, 1, '[{"type":"비고","hours":"0","etc":"순특공: 5시간"}]'::text),
  ('김인자', '5월', true, 98, 6, '[]'::text),
  ('김정남', '5월', true, 50, 0, '[]'::text),
  ('김정민', '5월', true, 38, 1, '[]'::text),
  ('김정숙', '5월', true, 45, 0, '[]'::text),
  ('김주연', '5월', true, 16, 0, '[{"type":"비고","hours":"0","etc":"베델봉사: 55시간"}]'::text),
  ('김준', '5월', true, 45, 0, '[{"type":"비고","hours":"0","etc":"순특공: 5시간"}]'::text),
  ('김지애', '5월', true, 0, 0, '[]'::text),
  ('김태민', '5월', true, 45, 0, '[]'::text),
  ('김태호', '5월', true, 0, 0, '[]'::text),
  ('김하나', '5월', true, 0, 0, '[]'::text),
  ('김하연', '5월', true, 39, 0, '[{"type":"비고","hours":"0","etc":"LDC: 28시간"}]'::text),
  ('김홍철', '5월', true, 0, 0, '[]'::text),
  ('김희웅', '5월', true, 63, 0, '[]'::text),
  ('김희정', '5월', true, 51, 0, '[]'::text),
  ('문경주', '5월', true, 32, 1, '[{"type":"비고","hours":"0","etc":"원격봉사: 45시간"}]'::text),
  ('문광호', '5월', true, 52, 0, '[]'::text),
  ('문정은', '5월', true, 50, 0, '[]'::text),
  ('박근미', '5월', true, 0, 0, '[]'::text),
  ('박미희', '5월', true, 58, 0, '[]'::text),
  ('박해숙', '5월', true, 50, 0, '[]'::text),
  ('박형빈', '5월', true, 50, 0, '[]'::text),
  ('손지영', '5월', true, 62, 2, '[]'::text),
  ('신경희', '5월', true, 0, 0, '[]'::text),
  ('신미연', '5월', true, 0, 0, '[{"type":"비고","hours":"0","etc":"기타: 1시간"}]'::text),
  ('신범선', '5월', true, 58, 2, '[]'::text),
  ('심인숙', '5월', true, 17, 0, '[]'::text),
  ('오경숙', '5월', true, 0, 0, '[]'::text),
  ('우성제', '5월', true, 0, 0, '[]'::text),
  ('위영희', '5월', true, 53, 0, '[]'::text),
  ('이경진', '5월', true, 68, 0, '[]'::text),
  ('이경훈', '5월', true, 32, 0, '[]'::text),
  ('이기운', '5월', true, 140, 1, '[]'::text),
  ('이순금', '5월', true, 0, 0, '[]'::text),
  ('이순주', '5월', true, 54, 2, '[]'::text),
  ('이슬아', '5월', true, 68, 0, '[]'::text),
  ('이용규', '5월', true, 0, 0, '[]'::text),
  ('이은옥', '5월', true, 0, 0, '[]'::text),
  ('이은우', '5월', true, 0, 0, '[{"type":"비고","hours":"0","etc":"전입"}]'::text),
  ('이재춘', '5월', true, 0, 0, '[]'::text),
  ('이정구', '5월', true, 31, 1, '[]'::text),
  ('이정인', '5월', true, 72, 1, '[]'::text),
  ('이채민', '5월', true, 0, 0, '[]'::text),
  ('이춘자', '5월', true, 0, 0, '[]'::text),
  ('이혜미', '5월', true, 66, 2, '[]'::text),
  ('이혜숙', '5월', true, 67, 0, '[]'::text)
) AS v(name, month, participated, hours, bible_studies, remarks)
CROSS JOIN (SELECT id FROM public.service_years WHERE year_name = '2025' LIMIT 1) sy
JOIN public.publishers p ON p.name = v.name
ON CONFLICT (service_year_id, publisher_id, month) 
DO UPDATE SET 
  participated = EXCLUDED.participated,
  hours = EXCLUDED.hours,
  bible_studies = EXCLUDED.bible_studies,
  remarks = EXCLUDED.remarks;

INSERT INTO public.monthly_reports (service_year_id, publisher_id, month, participated, hours, bible_studies, remarks, submitted_at)
SELECT 
  sy.id,
  p.id,
  v.month,
  v.participated,
  v.hours,
  v.bible_studies,
  v.remarks::JSONB,
  '2024-09-01 00:00:00+00'::TIMESTAMPTZ
FROM (VALUES
  ('인혜진', '5월', true, 56, 1, '[]'::text),
  ('임연순', '5월', true, 50, 0, '[]'::text),
  ('장정자', '5월', true, 0, 0, '[]'::text),
  ('장지은', '5월', true, 57, 1, '[]'::text),
  ('전은아', '5월', true, 53, 1, '[]'::text),
  ('전인숙', '5월', true, 58, 2, '[]'::text),
  ('전재관', '5월', true, 61, 3, '[{"type":"비고","hours":"0","etc":"유지보수: 2시간"}]'::text),
  ('전지훈', '5월', true, 53, 1, '[]'::text),
  ('전진혁', '5월', true, 0, 0, '[]'::text),
  ('전채균', '5월', true, 0, 0, '[]'::text),
  ('전혜인', '5월', true, 62, 1, '[]'::text),
  ('전호진', '5월', true, 45, 0, '[]'::text),
  ('정금석', '5월', true, 0, 0, '[]'::text),
  ('정명희', '5월', true, 0, 0, '[]'::text),
  ('정복희', '5월', true, 52, 0, '[]'::text),
  ('정승헌', '5월', true, 47, 0, '[]'::text),
  ('정태희', '5월', true, 60, 0, '[]'::text),
  ('정향순', '5월', true, 0, 0, '[]'::text),
  ('조월동', '5월', true, 0, 0, '[]'::text),
  ('조인형', '5월', true, 71, 1, '[]'::text),
  ('조행진', '5월', true, 45, 0, '[]'::text),
  ('주우규', '5월', true, 82, 0, '[]'::text),
  ('진선미', '5월', true, 0, 0, '[]'::text),
  ('채영진', '5월', true, 50, 0, '[]'::text),
  ('최선율', '5월', true, 0, 0, '[]'::text),
  ('최수정', '5월', true, 0, 0, '[]'::text),
  ('최승준', '5월', true, 65, 1, '[]'::text),
  ('최현수', '5월', true, 0, 1, '[]'::text),
  ('한명숙', '5월', true, 33, 1, '[]'::text),
  ('허율', '5월', true, 0, 0, '[]'::text),
  ('황선영', '5월', true, 0, 0, '[]'::text),
  ('황은영', '5월', true, 0, 0, '[]'::text),
  ('강미숙', '6월', true, 0, 0, '[]'::text),
  ('강석찬', '6월', true, 38, 0, '[{"type":"비고","hours":"0","etc":"대회자원봉사: 13시간"}]'::text),
  ('강선아', '6월', true, 32, 0, '[]'::text),
  ('강영아', '6월', true, 0, 0, '[]'::text),
  ('강정구', '6월', true, 38, 0, '[]'::text),
  ('권선', '6월', true, 50, 0, '[]'::text),
  ('권윤', '6월', true, 50, 0, '[]'::text),
  ('김기림', '6월', true, 50, 0, '[]'::text),
  ('김랑임', '6월', true, 0, 0, '[]'::text),
  ('김명철', '6월', true, 0, 0, '[]'::text),
  ('김명희', '6월', true, 40, 0, '[]'::text),
  ('김미옥', '6월', true, 0, 0, '[]'::text),
  ('김상만', '6월', true, 0, 0, '[]'::text),
  ('김승연', '6월', true, 41, 0, '[]'::text),
  ('김승일', '6월', true, 40, 1, '[]'::text),
  ('김인자', '6월', true, 75, 5, '[]'::text),
  ('김정남', '6월', true, 50, 0, '[]'::text),
  ('김정민', '6월', true, 40, 1, '[]'::text),
  ('김정숙', '6월', true, 37, 0, '[]'::text),
  ('김주연', '6월', true, 20, 0, '[{"type":"비고","hours":"0","etc":"베델봉사: 55시간"}]'::text),
  ('김준', '6월', true, 26, 0, '[{"type":"비고","hours":"0","etc":"대회자원봉사: 6시간"}]'::text),
  ('김지애', '6월', true, 0, 0, '[]'::text),
  ('김태민', '6월', true, 43, 0, '[]'::text),
  ('김태호', '6월', true, 0, 0, '[]'::text),
  ('김하나', '6월', true, 0, 0, '[]'::text),
  ('김하연', '6월', true, 20, 0, '[{"type":"비고","hours":"0","etc":"LDC: 36시간"}]'::text),
  ('김홍철', '6월', true, 0, 0, '[]'::text),
  ('김희웅', '6월', true, 36, 0, '[]'::text),
  ('김희정', '6월', true, 50, 0, '[]'::text),
  ('문경주', '6월', true, 25, 1, '[{"type":"비고","hours":"0","etc":"원격봉사: 35시간"}]'::text),
  ('문광호', '6월', true, 51, 0, '[]'::text),
  ('문정은', '6월', true, 45, 0, '[]'::text),
  ('박근미', '6월', true, 0, 0, '[]'::text),
  ('박미희', '6월', true, 51, 0, '[]'::text),
  ('박해숙', '6월', true, 6, 0, '[]'::text),
  ('박형빈', '6월', true, 45, 0, '[]'::text),
  ('손지영', '6월', true, 46, 2, '[]'::text),
  ('신경희', '6월', true, 0, 0, '[]'::text),
  ('신미연', '6월', true, 0, 0, '[]'::text),
  ('신범선', '6월', true, 40, 2, '[]'::text),
  ('심인숙', '6월', true, 46, 0, '[]'::text),
  ('오경숙', '6월', true, 0, 0, '[]'::text),
  ('우성제', '6월', true, 0, 0, '[]'::text),
  ('위영희', '6월', false, 0, 0, '[]'::text),
  ('이경진', '6월', true, 44, 0, '[]'::text),
  ('이경훈', '6월', true, 0, 0, '[]'::text),
  ('이기운', '6월', true, 140, 1, '[]'::text),
  ('이순금', '6월', true, 0, 0, '[]'::text),
  ('이순주', '6월', true, 51, 2, '[]'::text),
  ('이슬아', '6월', true, 40, 0, '[]'::text),
  ('이용규', '6월', true, 0, 0, '[]'::text),
  ('이은옥', '6월', true, 0, 0, '[]'::text),
  ('이은우', '6월', true, 0, 0, '[]'::text),
  ('이재춘', '6월', true, 0, 0, '[]'::text),
  ('이정구', '6월', true, 33, 1, '[]'::text),
  ('이정인', '6월', true, 46, 1, '[]'::text),
  ('이채민', '6월', true, 0, 0, '[]'::text),
  ('이춘자', '6월', true, 0, 0, '[]'::text),
  ('이혜미', '6월', true, 56, 3, '[{"type":"비고","hours":"0","etc":"대회자원봉사: 8시간"}]'::text),
  ('이혜숙', '6월', true, 41, 0, '[]'::text),
  ('인혜진', '6월', true, 58, 1, '[]'::text),
  ('임연순', '6월', true, 50, 0, '[]'::text),
  ('장정자', '6월', true, 0, 0, '[]'::text),
  ('장지은', '6월', true, 54, 0, '[]'::text),
  ('전은아', '6월', true, 51, 1, '[{"type":"비고","hours":"0","etc":"대회자원봉사: 1시간"}]'::text),
  ('전인숙', '6월', true, 72, 3, '[]'::text),
  ('전재관', '6월', true, 55, 3, '[{"type":"비고","hours":"0","etc":"대회자원봉사: 8시간"}]'::text),
  ('전지훈', '6월', true, 55, 2, '[]'::text)
) AS v(name, month, participated, hours, bible_studies, remarks)
CROSS JOIN (SELECT id FROM public.service_years WHERE year_name = '2025' LIMIT 1) sy
JOIN public.publishers p ON p.name = v.name
ON CONFLICT (service_year_id, publisher_id, month) 
DO UPDATE SET 
  participated = EXCLUDED.participated,
  hours = EXCLUDED.hours,
  bible_studies = EXCLUDED.bible_studies,
  remarks = EXCLUDED.remarks;

INSERT INTO public.monthly_reports (service_year_id, publisher_id, month, participated, hours, bible_studies, remarks, submitted_at)
SELECT 
  sy.id,
  p.id,
  v.month,
  v.participated,
  v.hours,
  v.bible_studies,
  v.remarks::JSONB,
  '2024-09-01 00:00:00+00'::TIMESTAMPTZ
FROM (VALUES
  ('전진혁', '6월', true, 0, 0, '[]'::text),
  ('전채균', '6월', true, 0, 0, '[]'::text),
  ('전혜인', '6월', true, 46, 1, '[]'::text),
  ('전호진', '6월', true, 42, 0, '[]'::text),
  ('정금석', '6월', true, 0, 0, '[]'::text),
  ('정명희', '6월', true, 0, 0, '[]'::text),
  ('정복희', '6월', true, 50, 0, '[]'::text),
  ('정승헌', '6월', true, 52, 1, '[]'::text),
  ('정태희', '6월', true, 48, 0, '[]'::text),
  ('정향순', '6월', true, 0, 0, '[]'::text),
  ('조월동', '6월', true, 0, 0, '[]'::text),
  ('조인형', '6월', true, 27, 0, '[]'::text),
  ('조행진', '6월', true, 36, 0, '[]'::text),
  ('주우규', '6월', true, 56, 0, '[]'::text),
  ('진선미', '6월', true, 0, 0, '[]'::text),
  ('채영진', '6월', true, 47, 0, '[]'::text),
  ('최선율', '6월', true, 0, 0, '[]'::text),
  ('최수정', '6월', true, 0, 0, '[]'::text),
  ('최승준', '6월', true, 44, 1, '[]'::text),
  ('최현수', '6월', true, 0, 1, '[]'::text),
  ('한명숙', '6월', true, 25, 1, '[]'::text),
  ('허율', '6월', true, 0, 0, '[]'::text),
  ('황선영', '6월', true, 0, 0, '[]'::text),
  ('황은영', '6월', true, 0, 0, '[]'::text),
  ('강미숙', '7월', true, 0, 0, '[]'::text),
  ('강석찬', '7월', true, 51, 0, '[]'::text),
  ('강선아', '7월', true, 91, 0, '[]'::text),
  ('강영아', '7월', true, 0, 0, '[]'::text),
  ('강정구', '7월', true, 25, 0, '[]'::text),
  ('권선', '7월', true, 54, 0, '[]'::text),
  ('권윤', '7월', true, 50, 0, '[]'::text),
  ('김기림', '7월', true, 52, 0, '[]'::text),
  ('김랑임', '7월', true, 0, 0, '[]'::text),
  ('김명철', '7월', true, 0, 0, '[]'::text),
  ('김명희', '7월', true, 31, 0, '[]'::text),
  ('김미옥', '7월', true, 0, 0, '[]'::text),
  ('김상만', '7월', true, 0, 0, '[]'::text),
  ('김승연', '7월', true, 0, 0, '[]'::text),
  ('김승일', '7월', true, 35, 1, '[{"type":"비고","hours":"0","etc":"대회자원봉사: 10시간"}]'::text),
  ('김인자', '7월', true, 107, 4, '[]'::text),
  ('김정남', '7월', true, 50, 0, '[]'::text),
  ('김정민', '7월', true, 37, 1, '[]'::text),
  ('김정숙', '7월', true, 23, 0, '[]'::text),
  ('김주연', '7월', true, 20, 0, '[{"type":"비고","hours":"0","etc":"베델봉사: 55시간"}]'::text),
  ('김준', '7월', true, 40, 0, '[]'::text),
  ('김지애', '7월', true, 0, 0, '[]'::text),
  ('김태민', '7월', true, 60, 0, '[]'::text),
  ('김태호', '7월', true, 0, 0, '[]'::text),
  ('김하나', '7월', true, 0, 0, '[]'::text),
  ('김하연', '7월', true, 28, 0, '[{"type":"비고","hours":"0","etc":"LDC: 49시간"}]'::text),
  ('김홍철', '7월', true, 0, 0, '[]'::text),
  ('김희웅', '7월', true, 50, 0, '[]'::text),
  ('김희정', '7월', true, 55, 0, '[]'::text),
  ('문경주', '7월', true, 30, 1, '[{"type":"비고","hours":"0","etc":"원격봉사: 35시간, 대회자원봉사: 12시간"}]'::text),
  ('문광호', '7월', true, 50, 0, '[]'::text),
  ('문정은', '7월', true, 50, 0, '[]'::text),
  ('박근미', '7월', true, 0, 0, '[]'::text),
  ('박미희', '7월', true, 55, 0, '[]'::text),
  ('박해숙', '7월', true, 50, 0, '[]'::text),
  ('박형빈', '7월', true, 48, 0, '[]'::text),
  ('손지영', '7월', true, 37, 2, '[]'::text),
  ('신경희', '7월', true, 0, 0, '[]'::text),
  ('신미연', '7월', true, 0, 0, '[]'::text),
  ('신범선', '7월', true, 31, 2, '[]'::text),
  ('심인숙', '7월', true, 37, 0, '[]'::text),
  ('오경숙', '7월', true, 0, 0, '[]'::text),
  ('우성제', '7월', true, 0, 0, '[]'::text),
  ('위영희', '7월', false, 0, 0, '[]'::text),
  ('이경진', '7월', true, 46, 0, '[{"type":"비고","hours":"0","etc":"대회 사전설치 및 철거 2일: 10시간"}]'::text),
  ('이경훈', '7월', true, 34, 0, '[]'::text),
  ('이기운', '7월', true, 145, 2, '[]'::text),
  ('이순금', '7월', true, 0, 0, '[]'::text),
  ('이순주', '7월', true, 35, 2, '[]'::text),
  ('이슬아', '7월', true, 53, 0, '[]'::text),
  ('이용규', '7월', true, 0, 0, '[]'::text),
  ('이은옥', '7월', true, 0, 0, '[]'::text),
  ('이은우', '7월', true, 0, 0, '[]'::text),
  ('이재춘', '7월', true, 0, 0, '[]'::text),
  ('이정구', '7월', true, 0, 1, '[]'::text),
  ('이정인', '7월', true, 50, 1, '[{"type":"비고","hours":"0","etc":"대회자원봉사: 8시간"}]'::text),
  ('이채민', '7월', true, 0, 0, '[]'::text),
  ('이춘자', '7월', true, 0, 0, '[]'::text),
  ('이혜미', '7월', true, 42, 2, '[]'::text),
  ('이혜숙', '7월', true, 50, 0, '[]'::text),
  ('인혜진', '7월', true, 59, 1, '[]'::text),
  ('임연순', '7월', true, 42, 0, '[]'::text),
  ('장지은', '7월', true, 42, 0, '[]'::text),
  ('전은아', '7월', true, 49, 1, '[{"type":"비고","hours":"0","etc":"대회자원봉사: 4시간"}]'::text),
  ('전인숙', '7월', true, 77, 3, '[]'::text),
  ('전재관', '7월', true, 44, 3, '[]'::text),
  ('전지훈', '7월', true, 62, 1, '[]'::text),
  ('전진혁', '7월', true, 0, 0, '[]'::text),
  ('전채균', '7월', true, 0, 0, '[]'::text),
  ('전혜인', '7월', true, 51, 1, '[]'::text),
  ('전호진', '7월', true, 20, 0, '[{"type":"비고","hours":"0","etc":"무릎수술 병가중"}]'::text),
  ('정금석', '7월', true, 0, 0, '[]'::text),
  ('정명희', '7월', true, 0, 0, '[]'::text),
  ('정복희', '7월', true, 53, 0, '[]'::text),
  ('정승헌', '7월', true, 48, 1, '[]'::text),
  ('정태희', '7월', true, 50, 0, '[]'::text)
) AS v(name, month, participated, hours, bible_studies, remarks)
CROSS JOIN (SELECT id FROM public.service_years WHERE year_name = '2025' LIMIT 1) sy
JOIN public.publishers p ON p.name = v.name
ON CONFLICT (service_year_id, publisher_id, month) 
DO UPDATE SET 
  participated = EXCLUDED.participated,
  hours = EXCLUDED.hours,
  bible_studies = EXCLUDED.bible_studies,
  remarks = EXCLUDED.remarks;

INSERT INTO public.monthly_reports (service_year_id, publisher_id, month, participated, hours, bible_studies, remarks, submitted_at)
SELECT 
  sy.id,
  p.id,
  v.month,
  v.participated,
  v.hours,
  v.bible_studies,
  v.remarks::JSONB,
  '2024-09-01 00:00:00+00'::TIMESTAMPTZ
FROM (VALUES
  ('정향순', '7월', true, 0, 0, '[]'::text),
  ('조월동', '7월', true, 0, 0, '[]'::text),
  ('조인형', '7월', true, 48, 0, '[{"type":"비고","hours":"0","etc":"대회자원봉사: 8시간"}]'::text),
  ('조행진', '7월', true, 50, 0, '[]'::text),
  ('주우규', '7월', true, 60, 0, '[]'::text),
  ('진선미', '7월', true, 0, 0, '[]'::text),
  ('채영진', '7월', true, 43, 0, '[]'::text),
  ('최선율', '7월', true, 0, 0, '[]'::text),
  ('최수정', '7월', true, 0, 0, '[]'::text),
  ('최승준', '7월', true, 45, 1, '[]'::text),
  ('최현수', '7월', true, 33, 0, '[]'::text),
  ('한명숙', '7월', true, 115, 1, '[]'::text),
  ('허율', '7월', true, 0, 0, '[]'::text),
  ('황선영', '7월', true, 0, 0, '[]'::text),
  ('황은영', '7월', true, 0, 0, '[]'::text),
  ('강미숙', '8월', true, 0, 0, '[]'::text),
  ('강석찬', '8월', true, 28, 0, '[]'::text),
  ('강선아', '8월', true, 91, 0, '[]'::text),
  ('강영아', '8월', true, 0, 0, '[]'::text),
  ('강정구', '8월', true, 11, 0, '[]'::text),
  ('권선', '8월', true, 25, 0, '[]'::text),
  ('권윤', '8월', true, 40, 0, '[]'::text),
  ('김기림', '8월', true, 61, 0, '[]'::text),
  ('김랑임', '8월', true, 0, 0, '[]'::text),
  ('김명희', '8월', true, 37, 0, '[]'::text),
  ('김미옥', '8월', true, 0, 0, '[]'::text),
  ('김상만', '8월', true, 0, 0, '[]'::text),
  ('김승연', '8월', true, 40, 0, '[]'::text),
  ('김승일', '8월', true, 38, 1, '[]'::text),
  ('김인자', '8월', true, 84, 3, '[]'::text),
  ('김정남', '8월', true, 55, 0, '[]'::text),
  ('김정민', '8월', true, 42, 1, '[]'::text),
  ('김정숙', '8월', true, 14, 0, '[]'::text),
  ('김주연', '8월', true, 20, 0, '[{"type":"비고","hours":"0","etc":"베델봉사: 40시간"}]'::text),
  ('김준', '8월', true, 42, 0, '[{"type":"비고","hours":"0","etc":"특별공개증거: 3시간"}]'::text),
  ('김지애', '8월', true, 0, 0, '[]'::text),
  ('김태민', '8월', true, 71, 0, '[]'::text),
  ('김태호', '8월', true, 0, 0, '[]'::text),
  ('김하나', '8월', true, 0, 0, '[]'::text),
  ('김하연', '8월', true, 30, 0, '[]'::text),
  ('김홍철', '8월', true, 0, 0, '[]'::text),
  ('김희웅', '8월', true, 18, 0, '[]'::text),
  ('김희정', '8월', true, 60, 0, '[]'::text),
  ('문경주', '8월', true, 25, 1, '[{"type":"비고","hours":"0","etc":"원격봉사: 15시간, LDC: 32시간"}]'::text),
  ('문광호', '8월', true, 18, 0, '[{"type":"비고","hours":"0","etc":"파이오니아학교: 30시간"}]'::text),
  ('문정은', '8월', true, 50, 0, '[]'::text),
  ('박근미', '8월', true, 0, 0, '[]'::text),
  ('박미희', '8월', true, 18, 0, '[]'::text),
  ('박해숙', '8월', true, 53, 0, '[]'::text),
  ('박형빈', '8월', true, 39, 0, '[]'::text),
  ('손지영', '8월', true, 41, 2, '[{"type":"비고","hours":"0","etc":"LDC: 16시간"}]'::text),
  ('신경희', '8월', true, 0, 0, '[]'::text),
  ('신미연', '8월', true, 0, 0, '[]'::text),
  ('신범선', '8월', true, 35, 2, '[]'::text),
  ('심인숙', '8월', true, 18, 0, '[]'::text),
  ('오경숙', '8월', true, 0, 0, '[]'::text),
  ('우성제', '8월', true, 0, 0, '[]'::text),
  ('위영희', '8월', false, 0, 0, '[]'::text),
  ('이경진', '8월', true, 49, 0, '[]'::text),
  ('이경훈', '8월', true, 31, 0, '[]'::text),
  ('이기운', '8월', true, 0, 2, '[]'::text),
  ('이순금', '8월', true, 0, 0, '[]'::text),
  ('이순주', '8월', true, 20, 2, '[{"type":"비고","hours":"0","etc":"파이오니아학교: 30시간"}]'::text),
  ('이슬아', '8월', true, 62, 0, '[]'::text),
  ('이용규', '8월', true, 0, 0, '[]'::text),
  ('이은옥', '8월', true, 0, 0, '[]'::text),
  ('이은우', '8월', true, 33, 0, '[]'::text),
  ('이재춘', '8월', true, 0, 0, '[]'::text),
  ('이정구', '8월', true, 0, 0, '[]'::text),
  ('이정인', '8월', true, 46, 1, '[]'::text),
  ('이채민', '8월', true, 0, 0, '[]'::text),
  ('이춘자', '8월', true, 0, 0, '[]'::text),
  ('이혜미', '8월', true, 43, 1, '[]'::text),
  ('이혜숙', '8월', true, 53, 0, '[{"type":"비고","hours":"0","etc":"파이오니아학교: 30시간"}]'::text),
  ('인혜진', '8월', true, 62, 1, '[]'::text),
  ('임연순', '8월', true, 20, 0, '[{"type":"비고","hours":"0","etc":"파이오니아학교: 30시간"}]'::text),
  ('장지은', '8월', true, 42, 0, '[]'::text),
  ('전은아', '8월', true, 53, 1, '[]'::text),
  ('전인숙', '8월', true, 67, 3, '[]'::text),
  ('전재관', '8월', true, 47, 3, '[]'::text),
  ('전지훈', '8월', true, 45, 1, '[{"type":"비고","hours":"0","etc":"파이오니아학교: 30시간"}]'::text),
  ('전진혁', '8월', true, 0, 0, '[]'::text),
  ('전채균', '8월', true, 0, 0, '[]'::text),
  ('전혜인', '8월', true, 63, 1, '[]'::text),
  ('전호진', '8월', true, 36, 0, '[]'::text),
  ('정금석', '8월', true, 0, 0, '[]'::text),
  ('정명희', '8월', true, 0, 0, '[]'::text),
  ('정복희', '8월', true, 25, 0, '[]'::text),
  ('정승헌', '8월', true, 49, 1, '[{"type":"비고","hours":"0","etc":"파이오니아학교: 30시간"}]'::text),
  ('정태희', '8월', true, 50, 0, '[]'::text),
  ('정향순', '8월', true, 0, 0, '[]'::text),
  ('조월동', '8월', true, 0, 0, '[]'::text),
  ('조인형', '8월', true, 36, 0, '[]'::text),
  ('조행진', '8월', true, 22, 0, '[{"type":"비고","hours":"0","etc":"파이오니아학교: 30시간"}]'::text),
  ('주우규', '8월', true, 58, 0, '[{"type":"비고","hours":"0","etc":"파이오니아학교: 30시간"}]'::text),
  ('진선미', '8월', true, 0, 0, '[]'::text),
  ('채영진', '8월', true, 51, 0, '[]'::text),
  ('최선율', '8월', true, 30, 0, '[]'::text),
  ('최수정', '8월', true, 0, 0, '[]'::text),
  ('최승준', '8월', true, 48, 1, '[]'::text)
) AS v(name, month, participated, hours, bible_studies, remarks)
CROSS JOIN (SELECT id FROM public.service_years WHERE year_name = '2025' LIMIT 1) sy
JOIN public.publishers p ON p.name = v.name
ON CONFLICT (service_year_id, publisher_id, month) 
DO UPDATE SET 
  participated = EXCLUDED.participated,
  hours = EXCLUDED.hours,
  bible_studies = EXCLUDED.bible_studies,
  remarks = EXCLUDED.remarks;

INSERT INTO public.monthly_reports (service_year_id, publisher_id, month, participated, hours, bible_studies, remarks, submitted_at)
SELECT 
  sy.id,
  p.id,
  v.month,
  v.participated,
  v.hours,
  v.bible_studies,
  v.remarks::JSONB,
  '2024-09-01 00:00:00+00'::TIMESTAMPTZ
FROM (VALUES
  ('최현수', '8월', true, 32, 0, '[]'::text),
  ('한명숙', '8월', true, 120, 1, '[]'::text),
  ('허율', '8월', true, 0, 0, '[]'::text),
  ('황선영', '8월', true, 0, 0, '[]'::text),
  ('황은영', '8월', true, 0, 0, '[]'::text)
) AS v(name, month, participated, hours, bible_studies, remarks)
CROSS JOIN (SELECT id FROM public.service_years WHERE year_name = '2025' LIMIT 1) sy
JOIN public.publishers p ON p.name = v.name
ON CONFLICT (service_year_id, publisher_id, month) 
DO UPDATE SET 
  participated = EXCLUDED.participated,
  hours = EXCLUDED.hours,
  bible_studies = EXCLUDED.bible_studies,
  remarks = EXCLUDED.remarks;
